(defun load-input (file-path)
  (with-temp-buffer
    (insert-file-contents file-path)
    (buffer-string)))

(defun parse-input (input-string)
  (thread-last (split-string input-string ",")
    (mapcar 'string-to-number)))

(defun opcode-to-op (n)
  (cond ((= n 1) '+)
        ((= n 2) '*)
        ((= n 99) "finish")
        (t "bad")))

(defun parse-instruction (n)
  (let ((opcode (mod n 100))
        (m1 (mod (/ n 100) 10))
        (m2 (mod (/ n 1000) 10))
        (m3 (mod (/ n 10000) 10)))
    (list opcode m1 m2 m3)))

(defun program-to-table (program)
  (let ((table (make-hash-table))
        (i 0))
    (dolist (n program)
      (puthash i n table)
      (setq i (1+ i)))
    table))

(defun get-input ()
  (string-to-number (read-string "input pls: ")))

(defun get-val (position-mode index table)
  (if (not position-mode)
      (gethash index table)
    (gethash (gethash index table) table)))

(defun run (program)
  (let ((result nil)
        (table (program-to-table program))
        (i 0)
        (done nil))
    (while (not done)
      (let* ((instruction (parse-instruction (gethash i table)))
             (opcode (first instruction))
             (m1 (= (second instruction) 0))
             (m2 (= (third instruction) 0))
             (m3 (= (fourth instruction) 0)))
        (cond ((= opcode 1)
               (let* ((a (get-val m1 (1+ i) table))
                      (b (get-val m2 (+ 2 i) table))
                      (out (gethash (+ 3 i) table)))
                 (puthash out (+ a b) table))
               (setq i (+ 4 i)))
              ((= opcode 2)
               (let* ((a (get-val m1 (1+ i) table))
                      (b (get-val m2 (+ 2 i) table))
                      (out (gethash (+ 3 i) table)))
                 (puthash out (* a b) table))
               (setq i (+ 4 i)))
              ((= opcode 3)
               (let ((in (get-input))
                     (out (gethash (1+ i) table)))
                 (puthash out in table))
               (setq i (+ 2 i)))
              ((= opcode 4)
               (let ((v (get-val m1 (1+ i) table)))
                 (print v))
               (setq i (+ 2 i)))
              ((= opcode 5)
               (let ((param1 (get-val m1 (1+ i) table))
                     (param2 (get-val m2 (+ 2 i) table)))
                 (if (not (= param1 0))
                     (setq i param2)
                   (setq i (+ 3 i)))))
              ((= opcode 6)
               (let ((param1 (get-val m1 (1+ i) table))
                     (param2 (get-val m2 (+ 2 i) table)))
                 (if (= param1 0)
                     (setq i param2)
                   (setq i (+ 3 i)))))
              ((= opcode 7)
               (let ((param1 (get-val m1 (1+ i) table))
                     (param2 (get-val m2 (+ 2 i) table))
                     (param3 (gethash (+ 3 i) table)))
                 (if (< param1 param2)
                     (puthash param3 1 table)
                   (puthash param3 0 table))
                 (setq i (+ 4 i))))
              ((= opcode 8)
               (let ((param1 (get-val m1 (1+ i) table))
                     (param2 (get-val m2 (+ 2 i) table))
                     (param3 (gethash (+ 3 i) table)))
                 (if (= param1 param2)
                     (puthash param3 1 table)
                   (puthash param3 0 table))
                 (setq i (+ 4 i))))
              ((= opcode 99)
               (setq result (gethash 0 table))
               (setq done t)))))
    result))

(run (parse-input "1,9,10,3,2,3,11,0,99,30,40,50"))
(run (parse-input "1,0,0,0,99"))
(run (parse-input "2,3,0,3,99"))
(run (parse-input "2,4,4,5,99,0"))
(run (parse-input "1,1,1,4,99,5,6,0,99"))
(run (parse-input "1002,4,3,4,33"))
(run (parse-input "1101,100,-1,4,0"))
(run (parse-input "3,0,4,0,99"))

(run (parse-input "3,9,8,9,10,9,4,9,99,-1,8"))
(run (parse-input "3,9,7,9,10,9,4,9,99,-1,8"))
(run (parse-input "3,3,1108,-1,8,3,4,3,99"))
(run (parse-input "3,3,1107,-1,8,3,4,3,99"))

(run (parse-input "3,21,1008,21,8,20,1005,20,22,107,8,21,20,1006,20,31,1106,0,36,98,0,0,1002,21,125,20,4,20,1105,1,46,104,999,1105,1,46,1101,1000,1,20,4,20,1105,1,46,98,99"))

(thread-first "input"
  load-input
  parse-input
  run)

(parse-instruction 1002)

(setq test-program '(1002 4 3 4 33))
